---
# =================================================================================
# Example playbook to install cockpit on guests.
# Create inventory file and call as such:
# ansible-playbook -i /etc/ansible/labHosts.ini installCockpit.yaml
# =================================================================================

- name: Install Cockpit on Ubuntu systems
  hosts: all
  become: true
  tasks:
    - name: Ensure apt cache is updated
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Cockpit package
      ansible.builtin.apt:
        name: cockpit
        state: present

    - name: Ensure Cockpit service is enabled and started
      ansible.builtin.systemd:
        name: cockpit
        enabled: yes
        state: started
